"""Per-process loopback authentication for the owning Electron shell.

The secret is generated by Electron for the child Runtime process and never
persisted. It authenticates only loopback requests carrying the exact secret;
remote and browser-extension clients continue through their own canonical auth
boundaries.
"""
from __future__ import annotations

import hmac
import os

from flask import request

from core.v4.security import AuthContext, _is_loopback


def install_desktop_auth(app) -> None:
    secret = str(os.environ.get("LUMIDM_DESKTOP_SECRET") or "")
    if not secret or app.extensions.get("lumi_v7_desktop_auth"):
        return

    functions = app.before_request_funcs.get(None, [])
    for index, handler in enumerate(list(functions)):
        if getattr(handler, "__name__", "") != "_lumi_auth_guard":
            continue
        original = handler

        def owned_desktop_guard():
            supplied = str(request.headers.get("X-Lumi-Desktop-Secret") or "")
            if (
                supplied
                and _is_loopback(request.remote_addr or "")
                and hmac.compare_digest(supplied, secret)
            ):
                request.environ["lumi.auth"] = AuthContext(
                    role="owner",
                    client_name="Lumi Electron shell",
                    token_kind="owned_desktop",
                )
                return None
            return original()

        owned_desktop_guard.__name__ = "_lumi_owned_desktop_auth_guard"
        functions[index] = owned_desktop_guard
        app.extensions["lumi_v7_desktop_auth"] = True
        return

    raise RuntimeError("Lumi security guard was not available for desktop authentication")
