"use strict";
const { contextBridge, ipcRenderer } = require("electron");
function normalizedCapacity(value){const outer=value&&typeof value==="object"?value:{};const result=outer.result&&typeof outer.result==="object"?outer.result:outer;const downloadMbps=Number(result.download_mbps||result.mbps||0);const uploadMbps=Number(result.upload_mbps||0);return{...outer,...result,capacity_bps:Number(result.capacity_bps||result.bps||result.download_bps||(downloadMbps?downloadMbps*125000:0)),upload_bps:Number(result.upload_bps||(uploadMbps?uploadMbps*125000:0)),ping_ms:Number(result.ping_ms||result.latency_ms||0)};}
contextBridge.exposeInMainWorld("electronApp",{
  pickFolder:()=>ipcRenderer.invoke("pick-folder"),openPath:value=>ipcRenderer.invoke("ttg-open-path",value),openExternal:value=>ipcRenderer.invoke("ttg-open-external",value),prepareBrowserExtension:()=>ipcRenderer.invoke("ttg-prepare-browser-extension"),isElectron:true,
  getDesktopSettings:()=>ipcRenderer.invoke("v5-desktop-settings-get"),saveDesktopSettings:value=>ipcRenderer.invoke("v5-desktop-settings-save",value),showWidget:()=>ipcRenderer.send("v5-widget-show"),checkForUpdates:(manual=false)=>ipcRenderer.invoke("v5-update-check",manual),getConnectionCapacity:async()=>normalizedCapacity(await ipcRenderer.invoke("v6-capacity-status")),runConnectionCapacityTest:async()=>normalizedCapacity(await ipcRenderer.invoke("v6-capacity-run")),windowControl:action=>ipcRenderer.invoke("ttg-window-control",action),getWindowState:()=>ipcRenderer.invoke("ttg-window-state"),getAppInfo:()=>ipcRenderer.invoke("ttg-app-info"),
  onWindowState:callback=>{if(typeof callback!=="function")return()=>{};const listener=(_event,value)=>callback(value||{});ipcRenderer.on("ttg-window-state-changed",listener);return()=>ipcRenderer.removeListener("ttg-window-state-changed",listener);},
  onUpdateStatus:callback=>{if(typeof callback!=="function")return()=>{};const listener=(_event,value)=>callback(value);ipcRenderer.on("v5-update-status",listener);return()=>ipcRenderer.removeListener("v5-update-status",listener);},
  onConnectionCapacity:callback=>{if(typeof callback!=="function")return()=>{};const listener=(_event,value)=>callback(normalizedCapacity(value));ipcRenderer.on("v6-capacity-status",listener);return()=>ipcRenderer.removeListener("v6-capacity-status",listener);},
  onServerState:callback=>{if(typeof callback!=="function")return()=>{};const listener=(_event,value)=>callback(value||{});ipcRenderer.on("lumi-server-state",listener);return()=>ipcRenderer.removeListener("lumi-server-state",listener);},
});
